# Path settings
raw_dataset_dir: 
- ../data/raw/X.pickle
- ../data/raw/y.pickle

# Data splitting
train_ratio : 0.7
validation_ratio : 0.2
test_ratio : 0.1

# Image parameters
IMAGE_WIDTH : 28
IMAGE_HEIGHT : 28
IMAGE_CHANNELS : 1